# Generated by Django 2.2.4 on 2020-02-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200217_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': [('can_mark_returned', 'Set book as returned!')]},
        ),
    ]
