# Generated by Django 2.2.4 on 2020-02-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200217_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': [('can_mark_returned', 'Set book as returned!'), ('ti_lol', 'Ti lol')]},
        ),
    ]
